//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public string number { get; set; }
        public System.DateTime dateOpen { get; set; }
        public decimal balance { get; set; }
        public bool capitalization { get; set; }
        public int numberTimesIncreased { get; set; }
        public int clientId { get; set; }
    }
}
